# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 01:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('camiones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordenadas_corridas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coordenadas', geoposition.fields.GeopositionField(max_length=42)),
            ],
            options={
                'verbose_name_plural': 'Coordenadas de Corridas',
            },
        ),
        migrations.CreateModel(
            name='Coordenadas_rutas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coordenadas', geoposition.fields.GeopositionField(blank=True, max_length=42)),
                ('order', models.IntegerField()),
                ('sentido', models.IntegerField(choices=[(1, 'Ida'), (2, 'Vuelta')], default=1)),
            ],
            options={
                'verbose_name_plural': 'Coordenadas de las Rutas',
            },
        ),
        migrations.CreateModel(
            name='Corridas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_final', models.DateTimeField(null=True)),
                ('status', models.IntegerField(choices=[(1, 'En proceso'), (2, 'Finalizada'), (3, 'En pausa'), (4, 'Cancelado')], default=1)),
                ('sentido', models.IntegerField(choices=[(1, 'Ida'), (2, 'Vuelta')], default=1)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camiones.Rutas')),
            ],
            options={
                'verbose_name_plural': 'Corridas',
            },
        ),
        migrations.AddField(
            model_name='catalogo_rutas',
            name='punto_final',
            field=geoposition.fields.GeopositionField(blank=True, max_length=42),
        ),
        migrations.AddField(
            model_name='catalogo_rutas',
            name='punto_inicio',
            field=geoposition.fields.GeopositionField(blank=True, max_length=42),
        ),
        migrations.AddField(
            model_name='coordenadas_rutas',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camiones.Catalogo_rutas'),
        ),
        migrations.AddField(
            model_name='coordenadas_corridas',
            name='corrida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camiones.Corridas'),
        ),
    ]
