# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 17:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camiones', '0002_auto_20161229_1102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corridas',
            options={'verbose_name_plural': 'Corridas'},
        ),
    ]
