# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camiones', '0002_auto_20170108_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corridas',
            name='fecha_final',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
