# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 17:07
from __future__ import unicode_literals

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('camiones', '0003_auto_20161229_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rutas',
            name='punto_final',
        ),
        migrations.RemoveField(
            model_name='rutas',
            name='punto_inicio',
        ),
        migrations.AddField(
            model_name='catalogo_rutas',
            name='punto_final',
            field=geoposition.fields.GeopositionField(blank=True, max_length=42),
        ),
        migrations.AddField(
            model_name='catalogo_rutas',
            name='punto_inicio',
            field=geoposition.fields.GeopositionField(blank=True, max_length=42),
        ),
    ]
