# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camiones', '0005_coordenadas_rutas'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordenadas_rutas',
            name='sentido',
            field=models.IntegerField(choices=[(1, 'Ida'), (2, 'Vuelta')], default=1),
        ),
    ]
