# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 22:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concesionarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('rfc', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=10)),
                ('ciudad', models.CharField(default='Aguascalientes', max_length=140)),
                ('estado', models.CharField(default='Aguascalientes', max_length=140)),
                ('latitud', models.CharField(max_length=25)),
                ('longitud', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Concesionarios',
            },
        ),
        migrations.CreateModel(
            name='Conductores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('licencia_de_conducir', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Conductores',
            },
        ),
        migrations.CreateModel(
            name='TipoTrabajador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Tipo de trabajadores',
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('curp', models.CharField(max_length=30)),
                ('rfc', models.CharField(max_length=15)),
                ('fecha_de_nacimiento', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_de_ingreso', models.DateTimeField(default=django.utils.timezone.now)),
                ('concesionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Concesionarios')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.TipoTrabajador')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Trabajadores',
            },
        ),
        migrations.AddField(
            model_name='conductores',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Trabajador'),
        ),
    ]
