# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 02:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pasajeros', '0002_auto_20161227_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='fecha_de_nacimiento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
