# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasajeros', '0003_auto_20170102_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentas',
            name='año',
            field=models.IntegerField(default=2017),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuentas',
            name='cvc',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuentas',
            name='mes_expiracion',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuentas',
            name='no_tarjeta',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
