# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasajeros', '0004_auto_20170102_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentas',
            name='tipo_tarjeta',
            field=models.CharField(choices=[('1', 'American Express'), ('2', 'Visa'), ('3', 'Mastercard')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
