# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 23:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pasajeros', '0005_cuentas_tipo_tarjeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentas',
            name='fecha_alta',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
